### ISSUE TITLE
NATS Jetstream support

### ISSUE THREAD

**Issue by gedw99** [danthegoodman1/FireScroll#28]
I know its shameless but would like to work on getting this working with nats jetstream.

We might though have to keep kafka support until we work out the the partitions ?

https://github.com/bruth will know the answer i bet...

related doc links:

https://docs.nats.io/nats-concepts/subject_mapping
https://docs.nats.io/nats-concepts/subject_mapping#deterministic-subject-token-partitioning

https://natsbyexample.com/examples/jetstream/partitions/cli

**Comment by danthegoodman1** [comment]
@gedw99 Yeah partitioning is the big issue, Kafka handles this for you, and Jetstream lacks this (at least as far as I can tell). 

Leader election would be needed, and if that was added then there would be a lot of other things I'd want to hook into that system like spreading out the backup nodes for partitions across replicas to reduce the individual node bandwidth usage uploading to S3.

In favor of keeping this simple I'd definitely want to avoid adding leader election, but I'm not opposed to making the log consumption an interface (and heck even the partition an interface so that other embedded DBs could be used).

But yeah the lack of auto-partitioning in Jetstream like how the Kafka protocol handles it becomes a non-starter unfortunately, but I'd love to add it in!

**Comment by danthegoodman1** [comment]
See https://github.com/danthegoodman1/FireScroll/issues/46#issuecomment-1573611730
