### ISSUE TITLE
Nats

### ISSUE THREAD

**Issue by gedw99** [danthegoodman1/FireScroll#46]
I get what this does .

I just could not work out why you don’t replace Kafka and red panda with nats . Nats has kv Store, can be setup as a global system with many data centers,etc.

The snapshotting the cockroach to s3 is good. Solves a trick issue.

Uf you’re interested let me know about the nats thing.

also nats is a backing Store for kine ( etcd ). So it can also be used as the upstream registry if needed . Nats replicates its multi version kv.

hope you don’t mind me making an issue with other options.

i really like this project

**Comment by danthegoodman1** [comment]
Hey @gedw99 , I admire your passion for NATS and am glad that you like FireScroll! But I really don't think NATS is the right fit.

The major appeal of Kafka/RedPanda is that it manages the partitioning natively. While this could be done manually with JetStream (a topic like `partitions.x` and each node specifies a single `x` for example), it's encumbering to manage and disables alternative deployment options such as fly.io where you might not be able to predictively name the nodes to map these partitions. And even that example restricts one node to one partition, this means you can't scale just by adding nodes unless you built that coordination yourself. You'd need either a consensus protocol like Raft, or use a consistent KV. Both of those would probably ~2x the code base size to integrate.

Kafka and RedPanda handle this mapping, which means there is an enormous amount of code that can be omitted to build this automation, or managerial overhead that can be avoided not having to manually map partitions.

Another benefit to using Kafka/RedPanda is that you can easily get managed providers, where with NATS it seems like the preferred option in the cloud realm is to self-host, which can be a non-starter for a lot of folks when it plays such a critical role in the integrity of the data.

As awesome as I think NATS is, I don't feel comfortable integrating and maintaing it due to lack of experience and extensive examples or documentation of it being used outside of Synadia content.
